# Gitlab CI configuration
stages:
  - lint
  - test

# common before scripts
.template-1: &common-prepare
  image: node:7-alpine
  before_script:
   - npm install

# Lint the styles and javascript
lint:
  stage: lint
  <<: *common-prepare
  script:
    - npm run lint

# Run tests
test:
  stage: test
  <<: *common-prepare
  script:
    - npm run test
