# Gitlab CI configuration
stages:
  - verify

# common before scripts
.template-1: &common-prepare
  image: node:7-alpine
  before_script:
   - npm install

# Lint and run tests
verify:
  stage: verify
  <<: *common-prepare
  script:
    - npm run verify
